language: node_js
node_js:
  - "7"

compiler: gcc
sudo: false

os:
  - linux

osx_image: xcode8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.8";
      export CXX="g++-4.8";
      export LINK="gcc-4.8";
      export LINKXX="g++-4.8";
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install homebrew/science/vips --with-webp --with-graphicsmagick;
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

install:
  - npm install mango-cli
  - node node_modules/mango-cli/bin/mango install

script:
  - node node_modules/mango-cli/bin/mango build

env:
  global:
    secure: "Dd1d+ai9xRVZG9pvCoK7GweDWH4GtGIILEEIH+Fu/PwI2tkoOp4b9I5rrRv+SoHhRsPu6lt5QWXKpjfPefrCLGzF/RPbRa9nogGX9qLPq/tYB6rsXC3qTECqm9Sq2PgA6LgreAEnL/5jcNRyjcjuNE7s2CEupB66P9+RQU8U7OfJGwSltKZVffot1dI/Dbhtsa0RLdiJYJmybzvfp1qRrGV0Pypkt3R0+XiuVEqITQHySvoqPVnEdSYRIeKJr3Tf6H9WOYN32k/noeZnFY2sn2YGZGD/bRn1wfG756PunRK3vldtPuqf3ek4RjAl12kobKkerUF34T2kb43CXz2nlf4hg0e3KSV2n7Ze/eBv+8bxq+yS3JpTNnS4+6KCsTjaX7Un95Xjev4FsRzv8VxkMRoflIPFVwSJwMG5lH861+Qww+v9lyEPKPY18eiFrcRZltfYLOrsVeD7tq+6psFhPuRxtgKnwre0N9QrffIM8n+1R4WU7rRzXpxR4blYs3dqfn+5yoLGjKC1OiXT2KNAX56Ar7+IW900GkGn+1E74l8nYA2utHxdBJ6eTIn9srJZ4hAHd6ZFBW5FerZJfdRwkvZXCMZp2/qRtb+SHv9rTBTf/cBOz0bCfDpis9Gg6QN5hGOPBdOGnGy+6erxbCryD6YqV6v7N+ahk0ECnx/i/g0=" # GH_TOKEN=xyz123

after_success:
  - GIT_REPO="https://$GH_TOKEN@github.com/Onset/slides-test.git"
  - cd dist
  - git init
  - git config user.email "travis@example.com"
  - git config user.name "Travis CI"
  - git add .
  - git commit -m "Deploy"
  - git push --force --quiet $GIT_REPO master:gh-pages

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
